// Builds the site mockup kit, `.claude/mockups/_kit/app-theme.js`: the app's
// theme (palettes, fonts, Nuxt UI's semantic tokens, the Sheet tokens) as a
// Tailwind stylesheet, so an HTML mockup can use the same classes as the Nuxt
// pages (`bg-elevated`, `text-muted`, `ring-accented`, `rounded-md`,
// `text-primary`, `font-display`). See `.claude/ui-mockups.md`. A mockup loads
// it before Tailwind's browser build:
//
//   <script src="../_kit/app-theme.js"></script>
//   <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
//
// Run `node scripts/mockup-kit.mjs` after changing the theme; `--check` exits
// with an error if the kit is out of date. Reads `app/assets/css/main.css` and
// `.nuxt/ui.css` (written by `nuxt prepare`, which `pnpm install` runs).
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const out = join(root, ".claude/mockups/_kit/app-theme.js");
const mainCss = readFileSync(join(root, "app/assets/css/main.css"), "utf8");
const uiCssPath = join(root, ".nuxt/ui.css");
if (!existsSync(uiCssPath)) {
  console.error("mockup-kit: .nuxt/ui.css is missing; run `pnpm install` (or `pnpm nuxt prepare`) first.");
  process.exit(1);
}
const uiCss = readFileSync(uiCssPath, "utf8");

// The body of the first block that starts with `opener` (balanced braces).
function block(css, opener) {
  const start = css.indexOf(opener);
  if (start === -1) throw new Error(`mockup-kit: no "${opener}" block`);
  let depth = 0;
  for (let i = css.indexOf("{", start); i < css.length; i++) {
    if (css[i] === "{") depth++;
    else if (css[i] === "}" && --depth === 0)
      return css.slice(css.indexOf("{", start) + 1, i);
  }
  throw new Error(`mockup-kit: unclosed "${opener}" block`);
}

// The app's role names (primary, secondary, neutral) point at its palettes,
// as `app/app.config.ts` sets them.
const appConfig = readFileSync(join(root, "app/app.config.ts"), "utf8");
const roles = {};
for (const role of ["primary", "secondary", "neutral"]) {
  const match = appConfig.match(new RegExp(`${role}:\\s*"([a-z]+)"`));
  if (!match) throw new Error(`mockup-kit: no ${role} color in app.config.ts`);
  roles[role] = match[1];
}
const shades = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950];
const roleScales = Object.entries(roles)
  .flatMap(([role, palette]) =>
    shades.map((shade) => `  --color-${role}-${shade}: var(--color-${palette}-${shade});`),
  )
  .join("\n");

// Nuxt UI's semantic utilities (text-muted, bg-elevated, ring-accented, ...)
// and its radius scale, from the theme Nuxt UI generates.
const semantic = block(uiCss, "@theme default inline")
  .split("\n")
  .map((line) => line.trim())
  .filter((line) =>
    /^--(text-color|background-color|border-color|ring-color|ring-offset-color|divide-color|outline-color|radius)-/.test(line),
  )
  .map((line) => `  ${line}`)
  .join("\n");

const css = `/* Generated by scripts/mockup-kit.mjs from app/assets/css/main.css; don't edit. */
@import "tailwindcss";
@theme static {${block(mainCss, "@theme static")}}
@theme inline {
${roleScales}
  --color-error: var(--ui-error);
  --color-success: var(--ui-success);
  --color-warning: var(--ui-warning);
  --color-info: var(--ui-info);
  --text-color-primary: var(--ui-primary);
  --text-color-secondary: var(--ui-secondary);
  --text-color-error: var(--ui-error);
  --background-color-primary: var(--ui-primary);
  --background-color-primary-soft: var(--ui-primary-soft);
  --background-color-secondary-soft: var(--ui-secondary-soft);
  --border-color-primary: var(--ui-primary);
  --ring-color-primary: var(--ui-primary);
${semantic}
}
:root {${block(mainCss, ":root")}}
:focus-visible {${block(mainCss, ":focus-visible")}}
body {
  background-color: var(--st-page);
  color: var(--ui-text);
  font-family: var(--font-sans);
  color-scheme: light;
  -webkit-font-smoothing: antialiased;
}
h1 { font-family: var(--font-display); }
`;

const fonts =
  "https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@600;700&family=Nunito+Sans:wght@400;600;700&family=JetBrains+Mono:wght@400;500&display=swap";

const js = `// Generated by scripts/mockup-kit.mjs; don't edit. The app's theme for site
// mockups (see .claude/ui-mockups.md). Load it before Tailwind's browser build.
(() => {
  const fonts = document.createElement("link");
  fonts.rel = "stylesheet";
  fonts.href = ${JSON.stringify(fonts)};
  document.head.append(fonts);
  const style = document.createElement("style");
  style.type = "text/tailwindcss";
  style.textContent = ${JSON.stringify(css)};
  document.head.append(style);
})();
`;

if (process.argv.includes("--check")) {
  const current = existsSync(out) ? readFileSync(out, "utf8") : "";
  if (current !== js) {
    console.error("mockup-kit: .claude/mockups/_kit/app-theme.js is out of date; run `node scripts/mockup-kit.mjs`.");
    process.exit(1);
  }
  console.log("mockup-kit: up to date");
} else {
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, js);
  console.log(`mockup-kit: wrote ${out.slice(root.length + 1)}`);
}
